# Generated by Django 5.1.15 on 2026-03-03 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Profile name (e.g., 'Malware Deep Dive', 'Quick IP Check').", max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('ioc_type', models.CharField(choices=[('hash_md5', 'Hash MD5'), ('hash_sha1', 'Hash SHA1'), ('hash_sha256', 'Hash SHA256'), ('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL')], db_index=True, help_text='The type of IOC this profile investigates.', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Pre-loaded system profile (not owned by a specific user).')),
            ],
            options={
                'verbose_name': 'Investigation Profile',
                'verbose_name_plural': 'Investigation Profiles',
                'db_table': 'investigation_profiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Execution order within this profile (lower = first).')),
                ('is_enabled', models.BooleanField(default=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=30, help_text="Max seconds to wait for this source's response.")),
            ],
            options={
                'verbose_name': 'Profile Source Config',
                'verbose_name_plural': 'Profile Source Configs',
                'db_table': 'profile_source_configs',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ExpectedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, help_text="If True, this field is essential for the profile's purpose.")),
                ('available_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_in_profiles', to='sources.availablefield')),
            ],
            options={
                'verbose_name': 'Expected Field',
                'verbose_name_plural': 'Expected Fields',
                'db_table': 'expected_fields',
            },
        ),
    ]
