# Generated by Django 5.1.15 on 2026-03-03 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilesourceconfig',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_configs', to='profiles.investigationprofile'),
        ),
        migrations.AddField(
            model_name='profilesourceconfig',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_configs', to='sources.source'),
        ),
        migrations.AddField(
            model_name='expectedfield',
            name='profile_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_fields', to='profiles.profilesourceconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='profilesourceconfig',
            unique_together={('profile', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='expectedfield',
            unique_together={('profile_source', 'available_field')},
        ),
    ]
