# Generated by Django 5.1.15 on 2026-03-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="entry_hash",
            field=models.CharField(
                default="",
                editable=False,
                help_text="SHA-256 hash of this entry's content + previous_hash.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="previous_hash",
            field=models.CharField(
                default="0000000000000000000000000000000000000000000000000000000000000000",
                editable=False,
                help_text="SHA-256 hash of the previous log entry (chain integrity).",
                max_length=64,
            ),
        ),
    ]
