# Generated by Django 5.1.15 on 2026-03-28 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_organization_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reputation_score",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Score from 0 to 1000. Affects vote weight in the community.",
                    ),
                ),
                (
                    "verified_analyst",
                    models.BooleanField(
                        default=False,
                        help_text="Verified analysts have maximum trust weight (1.0x).",
                    ),
                ),
                ("total_contributions", models.PositiveIntegerField(default=0)),
                ("disputed_contributions", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Reputation",
                "verbose_name_plural": "User Reputations",
                "db_table": "user_reputation",
            },
        ),
    ]
