# Generated by Django 5.1.15 on 2026-03-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_user_reputation"),
    ]

    operations = [
        # GIN index on audit_log.detail JSONB for fast lookups by action metadata
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS idx_audit_log_detail_gin ON audit_log USING GIN (detail);",
            reverse_sql="DROP INDEX IF EXISTS idx_audit_log_detail_gin;",
        ),
        # Index on audit_log.entry_hash for verify_chain() lookups
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS idx_audit_log_entry_hash ON audit_log (entry_hash);",
            reverse_sql="DROP INDEX IF EXISTS idx_audit_log_entry_hash;",
        ),
    ]
