# Generated by Django 5.1.15 on 2026-03-03 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Human-readable name (e.g., 'VirusTotal')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="URL-safe identifier (e.g., 'virustotal')", unique=True)),
                ('base_url', models.URLField(help_text='Base URL for API requests')),
                ('auth_type', models.CharField(choices=[('header', 'Header'), ('query_param', 'Query Parameter'), ('basic_auth', 'Basic Auth'), ('body_param', 'Body Parameter'), ('none', 'No Authentication')], default='header', max_length=20)),
                ('env_var_name', models.CharField(blank=True, default='', help_text="Environment variable name for the API key (e.g., 'VIRUSTOTAL_API_KEY')", max_length=100)),
                ('supported_ioc_types', models.JSONField(default=list, help_text="List of IOC types this source supports. E.g., ['hash_sha256', 'ip', 'domain']")),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=10, help_text='Maximum requests per minute for this source.')),
                ('default_ttl_seconds', models.PositiveIntegerField(default=86400, help_text='Default time-to-live for cached results from this source.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this source is enabled for queries.')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Default priority order (lower = queried first).')),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Intelligence Source',
                'verbose_name_plural': 'Intelligence Sources',
                'db_table': 'sources',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AvailableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ioc_type', models.CharField(choices=[('hash_md5', 'Hash MD5'), ('hash_sha1', 'Hash SHA1'), ('hash_sha256', 'Hash SHA256'), ('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL')], db_index=True, help_text='Which IOC type this field applies to.', max_length=20)),
                ('normalized_name', models.CharField(db_index=True, help_text="Normalized field name from the master taxonomy (e.g., 'malware_family').", max_length=100)),
                ('api_field_path', models.CharField(help_text="JSON path in the API response (e.g., 'popular_threat_classification.suggested_threat_label').", max_length=255)),
                ('classification', models.CharField(choices=[('required', 'Required'), ('core', 'Core'), ('optional', 'Optional')], default='core', help_text='Priority classification: required, core, or optional.', max_length=20)),
                ('data_type', models.CharField(default='str', help_text='Expected data type: str, int, float, bool, list, dict.', max_length=20)),
                ('transform_function', models.CharField(blank=True, default='', help_text="Name of the transform function to normalize this field (e.g., 'transform_detection_ratio').", max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_fields', to='sources.source')),
            ],
            options={
                'verbose_name': 'Available Field',
                'verbose_name_plural': 'Available Fields',
                'db_table': 'available_fields',
                'ordering': ['source', 'classification', 'normalized_name'],
                'indexes': [models.Index(fields=['normalized_name', 'ioc_type'], name='available_f_normali_9a3abc_idx')],
                'unique_together': {('source', 'ioc_type', 'normalized_name')},
            },
        ),
    ]
