# Generated by Django 5.1.15 on 2026-03-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(help_text='The IOC value (hash, IP, domain, URL).', max_length=2048)),
                ('ioc_type', models.CharField(choices=[('hash_md5', 'Hash MD5'), ('hash_sha1', 'Hash SHA1'), ('hash_sha256', 'Hash SHA256'), ('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL')], db_index=True, max_length=20)),
                ('first_investigated_at', models.DateTimeField(auto_now_add=True)),
                ('last_investigated_at', models.DateTimeField(auto_now=True)),
                ('times_investigated', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
                'db_table': 'indicators',
                'ordering': ['-last_investigated_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Indicator Tag',
                'verbose_name_plural': 'Indicator Tags',
                'db_table': 'indicator_tags',
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('error', 'Error')], db_index=True, default='pending', max_length=20)),
                ('coverage_score', models.FloatField(blank=True, help_text='Percentage of expected fields that were found (0.0 to 100.0).', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('shared_to_community', models.BooleanField(default=False, help_text='Whether results were copied to the community knowledge base.')),
                ('error_detail', models.TextField(blank=True, default='', help_text="Error details if status is 'error' or 'partial'.")),
            ],
            options={
                'verbose_name': 'Investigation',
                'verbose_name_plural': 'Investigations',
                'db_table': 'investigations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(db_index=True, help_text="Normalized field name (e.g., 'malware_family').", max_length=100)),
                ('value', models.JSONField(blank=True, help_text='The normalized value returned by the source.', null=True)),
                ('status', models.CharField(choices=[('found', 'Found'), ('not_found', 'Not Found'), ('error', 'Error'), ('timeout', 'Timeout')], db_index=True, max_length=20)),
                ('was_expected', models.BooleanField(default=True, help_text="Whether this field was in the analyst's expected fields list.")),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='How long the source took to respond (milliseconds).', null=True)),
                ('raw_response', models.JSONField(blank=True, help_text='Original API response for debugging (optional, can be large).', null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Investigation Result',
                'verbose_name_plural': 'Investigation Results',
                'db_table': 'investigation_results',
                'ordering': ['source', 'field_name'],
            },
        ),
    ]
