# Generated by Django 5.1.15 on 2026-03-03 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigations', '0001_initial'),
        ('profiles', '0001_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='created_by',
            field=models.ForeignKey(help_text='The first user to investigate this IOC.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_indicators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicatortag',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='investigations.indicator'),
        ),
        migrations.AddField(
            model_name='indicatortag',
            name='tagged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigation',
            name='analyst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigation',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='investigations.indicator'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='profile_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to='profiles.investigationprofile'),
        ),
        migrations.AddField(
            model_name='investigationresult',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='investigations.investigation'),
        ),
        migrations.AddField(
            model_name='investigationresult',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_results', to='sources.source'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['ioc_type', '-last_investigated_at'], name='indicators_ioc_typ_d47793_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('value', 'ioc_type')},
        ),
        migrations.AlterUniqueTogether(
            name='indicatortag',
            unique_together={('indicator', 'tag')},
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['analyst', '-created_at'], name='investigati_analyst_d38916_idx'),
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['status', '-created_at'], name='investigati_status_c19c44_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationresult',
            index=models.Index(fields=['investigation', 'source'], name='investigati_investi_8ae4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationresult',
            index=models.Index(fields=['field_name', 'status'], name='investigati_field_n_7822e5_idx'),
        ),
    ]
