# Generated by Django 5.1.15 on 2026-03-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigations", "0003_add_schema_version_to_result"),
    ]

    operations = [
        # Speeds up the DB-level cache check in the orchestrator:
        # InvestigationResult.filter(investigation__indicator=x, source=s, fetched_at__gte=cutoff)
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_inv_results_source_fetched
                ON investigation_results (source_id, fetched_at DESC);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_inv_results_source_fetched;",
        ),
        # Speeds up indicator lookup across investigations (used in cache query join)
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_investigations_indicator
                ON investigations (indicator_id);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_investigations_indicator;",
        ),
        # Speeds up community duplicate check:
        # CommunityResult.filter(community_indicator=ci, source=s, field_name=f)
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_community_results_dedup
                ON community_results (community_indicator_id, source_id, field_name);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_community_results_dedup;",
        ),
        # Note: audit_log indexes live in users app migrations
        # (after the entry_hash column is created).
    ]
