# Generated by Django 5.1.15 on 2026-03-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('times_investigated', models.PositiveIntegerField(default=1, help_text='How many times this IOC has been investigated by the community.')),
                ('last_enriched_at', models.DateTimeField(auto_now=True, help_text='Last time new data was contributed.')),
            ],
            options={
                'verbose_name': 'Community Indicator',
                'verbose_name_plural': 'Community Indicators',
                'db_table': 'community_indicators',
                'ordering': ['-last_enriched_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Context, observations, or analysis notes.')),
            ],
            options={
                'verbose_name': 'Community Note',
                'verbose_name_plural': 'Community Notes',
                'db_table': 'community_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(db_index=True, max_length=100)),
                ('value', models.JSONField(blank=True, null=True)),
                ('contributed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confidence_votes', models.PositiveIntegerField(default=0, help_text='Net positive confirmation votes.')),
            ],
            options={
                'verbose_name': 'Community Result',
                'verbose_name_plural': 'Community Results',
                'db_table': 'community_results',
                'ordering': ['-contributed_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfidenceVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('confirm', 'Confirm'), ('dispute', 'Dispute')], max_length=10)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Confidence Vote',
                'verbose_name_plural': 'Confidence Votes',
                'db_table': 'confidence_votes',
            },
        ),
    ]
