# Generated by Django 5.1.15 on 2026-03-03 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('investigations', '0001_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communityindicator',
            name='first_seen_by',
            field=models.ForeignKey(help_text='Credit to the analyst who first shared this IOC.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_discoveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityindicator',
            name='indicator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_entry', to='investigations.indicator'),
        ),
        migrations.AddField(
            model_name='communitynote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitynote',
            name='community_indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='community.communityindicator'),
        ),
        migrations.AddField(
            model_name='communityresult',
            name='community_indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='community.communityindicator'),
        ),
        migrations.AddField(
            model_name='communityresult',
            name='contributed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityresult',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_results', to='sources.source'),
        ),
        migrations.AddField(
            model_name='confidencevote',
            name='community_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.communityresult'),
        ),
        migrations.AddField(
            model_name='confidencevote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='communityresult',
            index=models.Index(fields=['community_indicator', 'field_name'], name='community_r_communi_faf434_idx'),
        ),
        migrations.AddIndex(
            model_name='communityresult',
            index=models.Index(fields=['contributed_by', '-contributed_at'], name='community_r_contrib_4d3b58_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='confidencevote',
            unique_together={('community_result', 'voter')},
        ),
    ]
