# Generated by Django 5.1.15 on 2026-07-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_communityresult_unique_community_result_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityresult",
            name="confidence_votes",
            field=models.IntegerField(
                default=0,
                help_text="Net score: confirm votes minus dispute votes. Can go negative.",
            ),
        ),
    ]
